---
- name: Install Zabbix Agent 2
  hosts: sre_servers
  become: true

  tasks:
    - name: Download Zabbix repository package
      ansible.builtin.get_url:
        url: https://repo.zabbix.com/zabbix/7.4/release/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest+ubuntu26.04_all.deb
        dest: /tmp/zabbix-release.deb
        mode: '0644'

    - name: Install Zabbix repository package
      ansible.builtin.apt:
        deb: /tmp/zabbix-release.deb

    - name: Update APT package cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install Zabbix Agent 2
      ansible.builtin.apt:
        name: zabbix-agent2
        state: present

    - name: Enable and start Zabbix Agent 2
      ansible.builtin.systemd:
        name: zabbix-agent2
        enabled: true
        state: started
