---
- name: Install Nginx
  hosts: sre_servers
  become: true

  tasks:
    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: true

    - name: Enable and start Nginx
      ansible.builtin.systemd:
        name: nginx
        enabled: true
        state: started
